---
title: "analysis - missing migrants"
author: "Ruimin Lin - 28757599"
date: '2022-05-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)
```

```{r}
missingMG2022 <- read_csv("data/missing_migrants/MissingMigrants-Global-2022-05-10--19_05_02.csv")

missingMG2021 <- read_csv("data/missing_migrants/MissingMigrants-Global-2022-05-10--21_27_42.csv")

missingMG2020 <- read_csv("data/missing_migrants/MissingMigrants-Global-2022-05-11--13_33_08.csv")

missingMG2019 <- read_csv("data/missing_migrants/MissingMigrants-Global-2022-05-10--22_06_47.csv")

missingMG2018 <- read_csv("data/missing_migrants/MissingMigrants-Global-2022-05-10--22_06_56.csv")

missingMG2017 <- read_csv("data/missing_migrants/MissingMigrants-Global-2022-05-10--23_37_54.csv")

missingMG2016 <- read_csv("data/missing_migrants/MissingMigrants-Global-2022-05-11--13_35_18.csv")

missingMG2015 <- read_csv("data/missing_migrants/MissingMigrants-Global-2022-05-11--13_34_24.csv")

missingMG2014 <- read_csv("data/missing_migrants/MissingMigrants-Global-2022-05-11--13_33_54.csv")

missingMG <- rbind(missingMG2022, missingMG2021,missingMG2020,
             missingMG2019, missingMG2018,missingMG2017,
             missingMG2016, missingMG2015,missingMG2014)
```

