---
title: "analysis-missing_migrants"
author: "Ruimin Lin - 28757599"
code-fold: true
theme: style/article.scss
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(themes360info)
library(leaflet)
library(patchwork)
```

- The missing migrants data is obtained from [Missing Migrants Project](https://missingmigrants.iom.int/).

```{r}
missingMG <- read_csv("data/Missing_Migrants_Global_Figures_allData.csv")
missingMG
```


```{r}
missingMG <- missingMG %>%
  mutate_at(vars(8:14),
            funs(ifelse(is.na(.),0,.)))
missingMG

# Converting NA values to 0, from columns `Number of Dead` to `Number of Children`. 
```

```{r}

missingMG$Coordinates <- 
  str_extract_all(missingMG$Coordinates, "(?<=\\().+?(?=\\))") %>%
  str_split(" ", 2)


missingMG <- missingMG %>%
  drop_na(Coordinates) %>%
  mutate(Coordinates = sapply(Coordinates, toString)) %>%
  separate(Coordinates,
           c("lon", "lat"),
           ",")

missingMG <- missingMG %>%
  drop_na(lon, lat) %>%
  mutate(lon = as.double(lon),
         lat = as.double(lat),
         `Incident year` = as.character(`Incident year`))

missingMGrecent <- 
  missingMG %>%
  filter(`Incident year` == 2020)
```


```{r}
leaflet(missingMGrecent) %>%
  addProviderTiles("Esri") %>%
  addMarkers(lng = ~lon,
             lat = ~lat)

#shapefile from http://thematicmapping.org/downloads/world_borders.php
```


#### death on the sea

```{r}
missingMG1 <- missingMG %>%
  select(`Incident year`,
         `Region of Incident`,
         `Total Number of Dead and Missing`)

# warning summarize
missingMG1 <- missingMG1 %>%
  group_by(`Incident year`, `Region of Incident`) %>%
  summarise(`Total Number of Dead and Missing` = sum(`Total Number of Dead and Missing`)) %>%
  ungroup()


missingMG1 <- missingMG1 %>%
  complete(`Incident year`,
           `Region of Incident`)

missingMG1[is.na(missingMG1)] <- 0



missingMG1a <- missingMG1 %>%
  group_by(`Region of Incident`) %>%
  summarise(`Region total` = sum(`Total Number of Dead and Missing`)) %>%
  mutate(pct = round((`Region total`/sum(`Region total`)),4),
         Label = paste0(round(pct*100,1), "%"))

missingMG1b <- missingMG1 %>%
  mutate(`Incident year` = as.character(`Incident year`)) %>%
  group_by(`Incident year`) %>%
  summarise(`Year total` = sum(`Total Number of Dead and Missing`)) %>%
  mutate(pct = round((`Year total`/sum(`Year total`)),4),
         Label = paste0(round(pct*100,1), "%"))
```

```{r}
hm1 <- missingMG1 %>%
  ggplot(aes(x = `Incident year`,
             y = `Region of Incident`,
             fill = `Total Number of Dead and Missing`)) +
  geom_tile(colour = "black") +
  geom_text(aes(label = `Total Number of Dead and Missing`),
            size = 3) +
  scale_fill_gradient(low = "white", high = "red") +
  theme_minimal() +
  guides(fill="none")


mp1 <- missingMG1a %>%
  ggplot(aes(x = `Region of Incident`, 
             y = pct,
             alpha = pct)) +
  geom_col(width = .7,
           fill = "red") +
  geom_text(aes(label = Label), hjust = -0.2, size = 3) +
  scale_y_continuous(expand = expansion(mult = c(.0, .25))) +
  theme_void() +
  scale_alpha_continuous(range = c(0.5, 1)) +
  guides(alpha="none") +
  coord_flip()

mp2 <- missingMG1b %>%
  ggplot(aes(x = `Incident year`,
             y = pct,
             alpha = pct)) +
  geom_col(width = .7,
           fill = "red") +
  geom_text(aes(label = Label), vjust = -0.5, size = 3) +
  scale_y_continuous(expand = expansion(mult = c(.0, .25))) +
  theme_void() +
  scale_alpha_continuous(range = c(0.5, 1)) +
  guides(alpha="none") +
    labs(title = toupper("Dead and Missing Migrants"),
       subtitle = toupper(paste(
         "Number of dead and missing migrants from reported",
         "incidents 2014-2022",
         sep = "\n")))

layoutm <- "
AA#
BBC
BBC
BBC
BBC"




mmp1 <- mp2 + hm1 + mp1 + plot_layout(design = layoutm)

mmp1
```


```{r}
missingMG %>%
  ggplot(aes(x = `Reported Month`,
             y = `Total Number of Dead and Missing`)) +
  geom_col(aes(fill = `Region of Incident`))
```


#### cause of death

```{r}
missingMG %>%
  ggplot(aes(x = `Cause of Death`)) +
  geom_bar() +
  facet_wrap(~`Region of Incident`)
```

